package dockerdeploy

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/omry/reploy/internal/deploy"
)

type UpdateOptions struct {
	Dir   string
	Pack  deploy.PackRef
	Force bool
}

type UpdateResult struct {
	Path      string
	Status    deploy.UpdateStatus
	Ownership string
	Reason    string
}

func Update(options UpdateOptions) ([]UpdateResult, error) {
	if options.Dir == "" {
		options.Dir = DefaultDeploymentDir
	}
	ref := options.Pack
	var state deploy.DeploymentState
	if ref.Raw == "" {
		loadedState, err := loadState(options.Dir)
		if err != nil {
			return nil, err
		}
		state = loadedState
		ref = state.Blueprint
	}
	if ref.Raw == "" {
		return nil, fmt.Errorf("blueprint reference is required")
	}
	var pack deploy.AppPack
	var err error
	if options.Pack.Raw == "" {
		pack, err = deploy.LoadResolvedPack(ref, state.RequestedBlueprintRef, state.ResolvedArtifact)
	} else {
		pack, err = deploy.LoadPack(ref)
	}
	if err != nil {
		return nil, err
	}
	bundle := state.Bundle
	if len(bundle.Roots) == 0 {
		bundle, err = inferBundleState(options.Dir, pack)
		if err != nil {
			return nil, err
		}
	}

	manifest, err := loadManifestOrNew(options.Dir)
	if err != nil {
		return nil, err
	}
	compose, err := renderComposeTemplate(pack, bundle.Roots)
	if err != nil {
		return nil, err
	}
	toolBinary, err := currentExecutableContent()
	if err != nil {
		return nil, err
	}

	results := []UpdateResult{}
	currentGenerated := map[string]bool{}
	updateGenerated := func(relativePath string, content []byte, executable bool) error {
		currentGenerated[filepath.ToSlash(relativePath)] = true
		status, err := deploy.UpdateGeneratedFile(options.Dir, relativePath, content, executable, &manifest, options.Force)
		if err != nil {
			return err
		}
		results = append(results, UpdateResult{Path: filepath.Join(options.Dir, relativePath), Status: status, Ownership: "generated", Reason: "synced from blueprint and reploy templates"})
		return nil
	}
	if err := updateGenerated(ComposeFileName, []byte(compose), false); err != nil {
		return nil, err
	}
	if err := updateGenerated("reploy", []byte(helperTemplate()), true); err != nil {
		return nil, err
	}
	if err := updateGenerated(ToolBinaryFileName, toolBinary, true); err != nil {
		return nil, err
	}
	if err := pruneRemovedGeneratedFiles(options.Dir, currentGenerated, &manifest, &results); err != nil {
		return nil, err
	}
	if err := updateDockerEnvFile(options.Dir, pack, &results); err != nil {
		return nil, err
	}
	requirements, err := runtimeRequirementsContent(pack, bundle.Roots)
	if err != nil {
		return nil, err
	}
	requirementsStatus, err := deploy.WriteFileIfChanged(filepath.Join(options.Dir, RequirementsFileName), ensureTrailingNewline(requirements), 0o644)
	if err != nil {
		return nil, err
	}
	results = append(results, UpdateResult{Path: filepath.Join(options.Dir, RequirementsFileName), Status: requirementsStatus, Ownership: "local", Reason: "projected selected bundle roots for Docker runtime"})
	if err := ensureDeploymentDirs(options.Dir, pack.Docker.DeploymentDirs, &results); err != nil {
		return nil, err
	}
	if err := ensureLocalDir(options.Dir, RuntimeDirName, &results); err != nil {
		return nil, err
	}
	stateStatus, err := writeStateIfChanged(options.Dir, pack, bundle)
	if err != nil {
		return nil, err
	}
	results = append(results, UpdateResult{Path: filepath.Join(options.Dir, StateFileName), Status: stateStatus, Ownership: "state", Reason: "recorded resolved deployment state"})
	manifestStatus, err := deploy.WriteDeploymentManifestIfChanged(filepath.Join(options.Dir, ManifestFileName), manifest)
	if err != nil {
		return nil, err
	}
	results = append(results, UpdateResult{Path: filepath.Join(options.Dir, ManifestFileName), Status: manifestStatus, Ownership: "state", Reason: "recorded generated file hashes"})
	return results, nil
}

func pruneRemovedGeneratedFiles(dir string, current map[string]bool, manifest *deploy.DeploymentManifest, results *[]UpdateResult) error {
	for relativePath, entry := range manifest.Files {
		if current[relativePath] {
			continue
		}
		path := filepath.Join(dir, filepath.FromSlash(relativePath))
		currentHash, err := deploy.HashFile(path)
		switch {
		case err == nil && currentHash == entry.SHA256:
			if err := os.Remove(path); err != nil {
				return err
			}
			*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusRemoved, Ownership: "generated", Reason: "removed file no longer generated by current blueprint"})
		case err == nil:
			*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusSkipped, Ownership: "local", Reason: "left locally edited file no longer generated by current blueprint"})
		case os.IsNotExist(err):
		default:
			return err
		}
		delete(manifest.Files, relativePath)
	}
	return nil
}

func loadState(dir string) (deploy.DeploymentState, error) {
	content, err := os.ReadFile(filepath.Join(dir, StateFileName))
	if err != nil {
		return deploy.DeploymentState{}, fmt.Errorf("read deployment state: %w", err)
	}
	var state deploy.DeploymentState
	if err := json.Unmarshal(content, &state); err != nil {
		return deploy.DeploymentState{}, fmt.Errorf("parse deployment state: %w", err)
	}
	return state, nil
}

func loadManifestOrNew(dir string) (deploy.DeploymentManifest, error) {
	manifest, err := deploy.LoadDeploymentManifest(filepath.Join(dir, ManifestFileName))
	if err == nil {
		return manifest, nil
	}
	if os.IsNotExist(err) {
		return deploy.NewDeploymentManifest("reploy update"), nil
	}
	return deploy.DeploymentManifest{}, err
}

func writeMissingLocalFile(dir string, relativePath string, content []byte, results *[]UpdateResult) error {
	return writeMissingLocalFileMode(dir, relativePath, content, 0o644, results)
}

func writeMissingLocalFileMode(dir string, relativePath string, content []byte, mode os.FileMode, results *[]UpdateResult) error {
	path := filepath.Join(dir, relativePath)
	if _, err := os.Stat(path); err == nil {
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpToDate, Ownership: "local", Reason: "operator-owned file already exists"})
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, content, mode); err != nil {
		return err
	}
	*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpdated, Ownership: "local", Reason: "created missing operator-owned file"})
	return nil
}

func updateDockerEnvFile(dir string, pack deploy.AppPack, results *[]UpdateResult) error {
	path := filepath.Join(dir, DockerEnvFileName)
	desired := []byte(defaultDockerEnv(pack))
	current, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if err := os.WriteFile(path, desired, 0o644); err != nil {
			return err
		}
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpdated, Ownership: "local", Reason: "created missing Docker environment file"})
		return nil
	}
	if string(current) == string(desired) {
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpToDate, Ownership: "local", Reason: "Docker environment already matches current defaults"})
		return nil
	}
	if isOldGeneratedDockerEnv(current) {
		if err := os.WriteFile(path, desired, 0o644); err != nil {
			return err
		}
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpdated, Ownership: "local", Reason: "migrated old unreleased Docker environment defaults"})
		return nil
	}
	cleaned := removeObsoleteDockerEnvKeys(current)
	if string(cleaned) != string(current) {
		if err := os.WriteFile(path, cleaned, 0o644); err != nil {
			return err
		}
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpdated, Ownership: "local", Reason: "removed obsolete Docker environment keys"})
		return nil
	}
	*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpToDate, Ownership: "local", Reason: "preserved operator-edited Docker environment"})
	return nil
}

func isOldGeneratedDockerEnv(content []byte) bool {
	text := string(content)
	return strings.Contains(text, "# Docker Compose settings for the Arbiter deployment.") &&
		strings.Contains(text, "ARBITER_IMAGE=")
}

func removeObsoleteDockerEnvKeys(content []byte) []byte {
	obsolete := map[string]bool{
		"ARBITER_APP_ENV_FILE":        true,
		"ARBITER_IMAGE":               true,
		"ARBITER_CONTAINER_NAME":      true,
		"ARBITER_CONTAINER_USER":      true,
		"ARBITER_RESTART":             true,
		"ARBITER_CONFIG_DIR":          true,
		"ARBITER_REQUIREMENTS_FILE":   true,
		"ARBITER_BUNDLE_DIR":          true,
		"ARBITER_RUNTIME_DIR":         true,
		"ARBITER_DATA_DIR":            true,
		"ARBITER_HOST_BIND":           true,
		"ARBITER_HOST_PORT":           true,
		"ARBITER_CONTAINER_PORT":      true,
		"ARBITER_PUBLIC_SCHEME":       true,
		"ARBITER_PUBLIC_BASE_URL":     true,
		"ARBITER_DOCKER_NETWORK_NAME": true,
		"ARBITER_RUNTIME_ROOT":        true,
		"ARBITER_PIP_VERBOSE":         true,
		"ARBITER_CONFIG_MOUNT":        true,
	}
	lines := strings.Split(string(content), "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			kept = append(kept, line)
			continue
		}
		key, _, ok := strings.Cut(trimmed, "=")
		if ok && obsolete[strings.TrimSpace(key)] {
			continue
		}
		kept = append(kept, line)
	}
	cleaned := strings.Join(kept, "\n")
	if len(content) > 0 && content[len(content)-1] == '\n' && !strings.HasSuffix(cleaned, "\n") {
		cleaned += "\n"
	}
	return []byte(cleaned)
}

func ensureDeploymentDirs(dir string, deploymentDirs deploy.DockerDeploymentDirs, results *[]UpdateResult) error {
	for _, relativeDir := range deploymentDirs.All() {
		if err := ensureLocalDir(dir, relativeDir, results); err != nil {
			return err
		}
	}
	return nil
}

func ensureLocalDir(dir string, relativeDir string, results *[]UpdateResult) error {
	path := filepath.Join(dir, relativeDir)
	if _, err := os.Stat(path); err == nil {
		*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpToDate, Ownership: "directory", Reason: "deployment directory already exists"})
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(path, 0o700); err != nil {
		return err
	}
	*results = append(*results, UpdateResult{Path: path, Status: deploy.UpdateStatusUpdated, Ownership: "directory", Reason: "created deployment directory"})
	return nil
}
